#!/bin/bash

# colors
NOC='\033[0m'       # Reset
BLA='\033[0;30m'    # Black
RED='\033[0;31m'    # Red
GRE='\033[0;32m'    # Green
YEL='\033[0;33m'    # Yellow
BLU='\033[0;34m'    # Blue
PUR='\033[0;35m'    # Purple
CYA='\033[0;36m'    # Cyan
WHI='\033[0;37m'    # White

clear
echo -e "${GRE}|||| help"
echo -e "${NOC}"
lsblk
echo -e "${GRE}"
echo -e "do dis:${WHI}"
echo " 1. connect to ethernet or usb tether"
echo " 2. choose a partition for root"
echo " 3. choose a partition for esp"
echo "    - esp partition will be mounted at /esp"
echo "..run 'cfdisk' if you gotta rearrange partitions"
echo " 4. run 'bash install /dev/root /dev/esp username computername'"
echo -e "${NOC}"
