#!/bin/bash

clear
echo "|||| help"
echo ""
echo " 1. connect to ethernet or usb tether"
echo " 2. choose a partition for root"
echo " 3. choose a partition for esp"
echo "    - esp partition will be mounted at /esp"
echo "..run 'cfdisk' if you gotta rearrange partitions"
echo " 4. run 'bash install /dev/root /dev/esp'"
lsblk
