#!/bin/bash

# colors
NOC='\033[0m'       # Reset
BLA='\033[0;30m'    # Black
RED='\033[0;31m'    # Red
GRE='\033[0;32m'    # Green
YEL='\033[0;33m'    # Yellow
BLU='\033[0;34m'    # Blue
PUR='\033[0;35m'    # Purple
CYA='\033[0;36m'    # Cyan
WHI='\033[0;37m'    # White

clear

# arg checker
whoops () {
	echo -e "${WHI}$1 args provided${NOC}"
	echo "run 'bash help'"
	exit 1
}
if [ $# -lt 3 ]; then
	whoops "too few"
fi
if [ $# -gt 3 ]; then
	whoops "too many"
fi

# are you sure
lsblk
echo -e "${RED}"
echo "GOING TO REFORMAT AND INSTALL $1 WITH ROOT"
echo "GOING TO REFORMAT AND INSTALL $2 WITH ESP"
echo -e "${NOC}"
while true; do
    echo -e "${RED}"
    read -p "ARE YOU SURE YOU WANT TO PROCEED? (y/N)" yn
    echo -e "${NOC}"
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo -e "${WHI}Please answer yes or no${NOC}";;
    esac
done

#
# install
#

loadkeys us
timedatectl set-ntp true

mkfs.ext4 $1
mount $1 /mnt
mkdir /mnt/efi
mkfs.fat -F 32 $2
mount $2 /mnt/efi

pacstrap /mnt base base-devel linux-zen linux-zen-headers linux-firmware intel-ucode zsh neovim pipewire pipewire-alsa pipewire-jack pipewire-pulse networkmanager grub efibootmgr vim

genfstab -U /mnt >> /mnt/etc/fstab

cat << EOF | arch-chroot /mnt
  ln -sf /usr/share/zoneinfo/UTC /etc/localtime
  hwclock --systohc
  echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
  locale-gen
  touch /etc/locale.conf
  echo LANG=en_US.UTF-8 >> /etc/locale.conf
  echo KEYMAP=us >> /etc/vconsole.conf
  touch /etc/hostname
  echo ychor >> /etc/hostname
  touch /etc/hosts
  echo -e "127.0.0.1\tlocalhost\n::\t\tlocalhost\n127.0.0.1\tychor" | tee /etc/hosts
  grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=ESP --removable
  echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
  grub-mkconfig -o /boot/grub/grub.cfg
  useradd -m $3 -s /bin/zsh
  echo "%$3 ALL=(ALL:ALL) ALL" | EDITOR='tee -a' visudo
EOF

clear

echo -e "${CYA}"
echo " 1. run 'passwd'"
echo " 2. run 'passwd $3'"
echo " 3. "

arch-chroot /mnt

#inarch () {
#       if [ $1 -eq 0 ]; then
#	        echo "i dont feel so good"
#        	exit 1
#       fi
#
#       arch-chroot /mnt $1
#}

#inarch "ln -sf /usr/share/zoneinfo/UTC /etc/localtime"
#inarch "hwclock --systohc"
#inarch "echo en_US.UTF-8 UTF-8 >> /etc/locale.gen"
#inarch "locale-gen"
#inarch "touch /etc/locale.conf"
#inarch "echo LANG=en_US.UTF-8 >> /etc/locale.conf"
#inarch "echo KEYMAP=us >> /etc/vconsole.conf"
#inarch "touch /etc/hostname"
#inarch "echo ychor >> /etc/hostname"
#inarch "passwd"
#inarch "grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=GRUB"
